### ISSUE TITLE
dockerhub.azk8s.cn

### ISSUE THREAD

**Issue by khs1994** [docker-practice/docker-registry-cn-mirror-test#2]

**Comment by khs1994** [comment]
@andyzhangx `dockerhub.azk8s.cn` **403 错误 **

**Comment by andyzhangx** [comment]
sorry, 目前 *.azk8s.cn 已经仅限于 Azure China IP 使用，不再对外提供服务, 如果确实有需求，可以联系akscn@microsoft.com 并提供IP地址，我们会根据需求 做决定是否对特定IP提供服务，谢谢理解。
