### ISSUE TITLE
mirror.baidubce.com

### ISSUE THREAD

**Issue by khs1994** [docker-practice/docker-registry-cn-mirror-test#6]

**Comment by gzm55** [comment]
baidu 这个好像在国内和国外用了不同的 ip, 国内解析的 ip 连接超时

**Comment by khs1994** [comment]
我这里使用感觉速度不错，可能每个地区体验不同。在腾讯云机器上连接不到，你是使用的云服务器吗。

**Comment by gzm55** [comment]
我测试过国内和国外的多个环境, 包括公有云/家庭网络/办公网络/国内电信机房等, 基本上就看解析的 ip 结果, 广东的 ip 可以用, 北京的不能访问

**Comment by JustinHuber** [comment]
Error response from daemon: Get "https://mirror.baidubce.com/v2/": dial tcp: lookup mirror.baidubce.com: no such host
  mirror.baidubce.com is outdated
  Error: X [ mirror.baidubce.com ] is outdated
